# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
INHERIT: mkdocs/base.yml  # use the shared AutoRA configuration by default

site_name: eXplainable Regression based AI 
repo_url: 'https://github.com/PsyRes-Osnabrueck-University/xrai'

nav:
- Home: 'BasicUsage.ipynb'
# - Quickstart: 'quickstart.md'
# - Examples:
#   - Basic Usage: 'Basic Usage.ipynb'
#   - Benchmar: 'Benchmark.ipynb'
